server:
  port: 9501

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:windawn@eureka1:7001/eureka,http://admin:windawn@eureka2:7002/eureka,http://admin:windawn@eureka3:7003/eureka
    register-with-eureka: false

spring:
  application:
    name:  mksd-zuul-gateway
zuul:
  routes:
    users:
      path: /users-proxy/**
      serviceId: mksd-prod-users
    prod:
      path: /prod-proxy/**
      serviceId: mksd-prod
  ignored-services:
    "*"
