package com.windawn.mksd.vo;

import java.util.Date;

public class CmdCommodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.cmd_id
     *
     * @mbggenerated
     */
    private Long cmdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.cmd_name
     *
     * @mbggenerated
     */
    private String cmdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.cmd_code
     *
     * @mbggenerated
     */
    private String cmdCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.cmd_brand
     *
     * @mbggenerated
     */
    private Long cmdBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.cmd_status
     *
     * @mbggenerated
     */
    private Integer cmdStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.putaway_time
     *
     * @mbggenerated
     */
    private Date putawayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.shelf_life
     *
     * @mbggenerated
     */
    private String shelfLife;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.produce_date
     *
     * @mbggenerated
     */
    private Date produceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.expiration_date
     *
     * @mbggenerated
     */
    private Date expirationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.supplier_id
     *
     * @mbggenerated
     */
    private Long supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.img_path
     *
     * @mbggenerated
     */
    private String imgPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.cc_cmd_type
     *
     * @mbggenerated
     */
    private Integer ccCmdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.prod_place
     *
     * @mbggenerated
     */
    private String prodPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.storage_condition
     *
     * @mbggenerated
     */
    private String storageCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.cc_price_id
     *
     * @mbggenerated
     */
    private Long ccPriceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_commodity.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.cmd_id
     *
     * @return the value of mk_cmd_commodity.cmd_id
     *
     * @mbggenerated
     */
    public Long getCmdId() {
        return cmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.cmd_id
     *
     * @param cmdId the value for mk_cmd_commodity.cmd_id
     *
     * @mbggenerated
     */
    public void setCmdId(Long cmdId) {
        this.cmdId = cmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.cmd_name
     *
     * @return the value of mk_cmd_commodity.cmd_name
     *
     * @mbggenerated
     */
    public String getCmdName() {
        return cmdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.cmd_name
     *
     * @param cmdName the value for mk_cmd_commodity.cmd_name
     *
     * @mbggenerated
     */
    public void setCmdName(String cmdName) {
        this.cmdName = cmdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.cmd_code
     *
     * @return the value of mk_cmd_commodity.cmd_code
     *
     * @mbggenerated
     */
    public String getCmdCode() {
        return cmdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.cmd_code
     *
     * @param cmdCode the value for mk_cmd_commodity.cmd_code
     *
     * @mbggenerated
     */
    public void setCmdCode(String cmdCode) {
        this.cmdCode = cmdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.cmd_brand
     *
     * @return the value of mk_cmd_commodity.cmd_brand
     *
     * @mbggenerated
     */
    public Long getCmdBrand() {
        return cmdBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.cmd_brand
     *
     * @param cmdBrand the value for mk_cmd_commodity.cmd_brand
     *
     * @mbggenerated
     */
    public void setCmdBrand(Long cmdBrand) {
        this.cmdBrand = cmdBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.cmd_status
     *
     * @return the value of mk_cmd_commodity.cmd_status
     *
     * @mbggenerated
     */
    public Integer getCmdStatus() {
        return cmdStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.cmd_status
     *
     * @param cmdStatus the value for mk_cmd_commodity.cmd_status
     *
     * @mbggenerated
     */
    public void setCmdStatus(Integer cmdStatus) {
        this.cmdStatus = cmdStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.create_time
     *
     * @return the value of mk_cmd_commodity.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.create_time
     *
     * @param createTime the value for mk_cmd_commodity.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.putaway_time
     *
     * @return the value of mk_cmd_commodity.putaway_time
     *
     * @mbggenerated
     */
    public Date getPutawayTime() {
        return putawayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.putaway_time
     *
     * @param putawayTime the value for mk_cmd_commodity.putaway_time
     *
     * @mbggenerated
     */
    public void setPutawayTime(Date putawayTime) {
        this.putawayTime = putawayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.shelf_life
     *
     * @return the value of mk_cmd_commodity.shelf_life
     *
     * @mbggenerated
     */
    public String getShelfLife() {
        return shelfLife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.shelf_life
     *
     * @param shelfLife the value for mk_cmd_commodity.shelf_life
     *
     * @mbggenerated
     */
    public void setShelfLife(String shelfLife) {
        this.shelfLife = shelfLife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.produce_date
     *
     * @return the value of mk_cmd_commodity.produce_date
     *
     * @mbggenerated
     */
    public Date getProduceDate() {
        return produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.produce_date
     *
     * @param produceDate the value for mk_cmd_commodity.produce_date
     *
     * @mbggenerated
     */
    public void setProduceDate(Date produceDate) {
        this.produceDate = produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.expiration_date
     *
     * @return the value of mk_cmd_commodity.expiration_date
     *
     * @mbggenerated
     */
    public Date getExpirationDate() {
        return expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.expiration_date
     *
     * @param expirationDate the value for mk_cmd_commodity.expiration_date
     *
     * @mbggenerated
     */
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.supplier_id
     *
     * @return the value of mk_cmd_commodity.supplier_id
     *
     * @mbggenerated
     */
    public Long getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.supplier_id
     *
     * @param supplierId the value for mk_cmd_commodity.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(Long supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.img_path
     *
     * @return the value of mk_cmd_commodity.img_path
     *
     * @mbggenerated
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.img_path
     *
     * @param imgPath the value for mk_cmd_commodity.img_path
     *
     * @mbggenerated
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.cc_cmd_type
     *
     * @return the value of mk_cmd_commodity.cc_cmd_type
     *
     * @mbggenerated
     */
    public Integer getCcCmdType() {
        return ccCmdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.cc_cmd_type
     *
     * @param ccCmdType the value for mk_cmd_commodity.cc_cmd_type
     *
     * @mbggenerated
     */
    public void setCcCmdType(Integer ccCmdType) {
        this.ccCmdType = ccCmdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.prod_place
     *
     * @return the value of mk_cmd_commodity.prod_place
     *
     * @mbggenerated
     */
    public String getProdPlace() {
        return prodPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.prod_place
     *
     * @param prodPlace the value for mk_cmd_commodity.prod_place
     *
     * @mbggenerated
     */
    public void setProdPlace(String prodPlace) {
        this.prodPlace = prodPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.storage_condition
     *
     * @return the value of mk_cmd_commodity.storage_condition
     *
     * @mbggenerated
     */
    public String getStorageCondition() {
        return storageCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.storage_condition
     *
     * @param storageCondition the value for mk_cmd_commodity.storage_condition
     *
     * @mbggenerated
     */
    public void setStorageCondition(String storageCondition) {
        this.storageCondition = storageCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.cc_price_id
     *
     * @return the value of mk_cmd_commodity.cc_price_id
     *
     * @mbggenerated
     */
    public Long getCcPriceId() {
        return ccPriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.cc_price_id
     *
     * @param ccPriceId the value for mk_cmd_commodity.cc_price_id
     *
     * @mbggenerated
     */
    public void setCcPriceId(Long ccPriceId) {
        this.ccPriceId = ccPriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_commodity.description
     *
     * @return the value of mk_cmd_commodity.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_commodity.description
     *
     * @param description the value for mk_cmd_commodity.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }
}