package com.windawn.mksd.vo;

import java.util.Date;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.supplier_id
     *
     * @mbggenerated
     */
    private String supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.plain_password
     *
     * @mbggenerated
     */
    private String plainPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.imgpath
     *
     * @mbggenerated
     */
    private String imgpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.dept_id
     *
     * @mbggenerated
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.portrait
     *
     * @mbggenerated
     */
    private String portrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.phone_code
     *
     * @mbggenerated
     */
    private String phoneCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.last_login
     *
     * @mbggenerated
     */
    private Date lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.last_device
     *
     * @mbggenerated
     */
    private String lastDevice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.last_ip
     *
     * @mbggenerated
     */
    private String lastIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.login_num
     *
     * @mbggenerated
     */
    private Integer loginNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.is_system
     *
     * @mbggenerated
     */
    private String isSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_position
     *
     * @mbggenerated
     */
    private String userPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.attr3
     *
     * @mbggenerated
     */
    private String attr3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.attr4
     *
     * @mbggenerated
     */
    private String attr4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.attr5
     *
     * @mbggenerated
     */
    private String attr5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.attr1
     *
     * @mbggenerated
     */
    private String attr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.attr2
     *
     * @mbggenerated
     */
    private String attr2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.uid
     *
     * @return the value of sys_user.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.uid
     *
     * @param uid the value for sys_user.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.supplier_id
     *
     * @return the value of sys_user.supplier_id
     *
     * @mbggenerated
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.supplier_id
     *
     * @param supplierId the value for sys_user.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_name
     *
     * @return the value of sys_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_name
     *
     * @param userName the value for sys_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.plain_password
     *
     * @return the value of sys_user.plain_password
     *
     * @mbggenerated
     */
    public String getPlainPassword() {
        return plainPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.plain_password
     *
     * @param plainPassword the value for sys_user.plain_password
     *
     * @mbggenerated
     */
    public void setPlainPassword(String plainPassword) {
        this.plainPassword = plainPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.imgpath
     *
     * @return the value of sys_user.imgpath
     *
     * @mbggenerated
     */
    public String getImgpath() {
        return imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.imgpath
     *
     * @param imgpath the value for sys_user.imgpath
     *
     * @mbggenerated
     */
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.real_name
     *
     * @return the value of sys_user.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.real_name
     *
     * @param realName the value for sys_user.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.dept_id
     *
     * @return the value of sys_user.dept_id
     *
     * @mbggenerated
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.dept_id
     *
     * @param deptId the value for sys_user.dept_id
     *
     * @mbggenerated
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.gender
     *
     * @return the value of sys_user.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.gender
     *
     * @param gender the value for sys_user.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.birthday
     *
     * @return the value of sys_user.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.birthday
     *
     * @param birthday the value for sys_user.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.portrait
     *
     * @return the value of sys_user.portrait
     *
     * @mbggenerated
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.portrait
     *
     * @param portrait the value for sys_user.portrait
     *
     * @mbggenerated
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.tel
     *
     * @return the value of sys_user.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.tel
     *
     * @param tel the value for sys_user.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.phone
     *
     * @return the value of sys_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.phone
     *
     * @param phone the value for sys_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.qq
     *
     * @return the value of sys_user.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.qq
     *
     * @param qq the value for sys_user.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.email
     *
     * @return the value of sys_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.email
     *
     * @param email the value for sys_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.phone_code
     *
     * @return the value of sys_user.phone_code
     *
     * @mbggenerated
     */
    public String getPhoneCode() {
        return phoneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.phone_code
     *
     * @param phoneCode the value for sys_user.phone_code
     *
     * @mbggenerated
     */
    public void setPhoneCode(String phoneCode) {
        this.phoneCode = phoneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.last_login
     *
     * @return the value of sys_user.last_login
     *
     * @mbggenerated
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.last_login
     *
     * @param lastLogin the value for sys_user.last_login
     *
     * @mbggenerated
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.last_device
     *
     * @return the value of sys_user.last_device
     *
     * @mbggenerated
     */
    public String getLastDevice() {
        return lastDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.last_device
     *
     * @param lastDevice the value for sys_user.last_device
     *
     * @mbggenerated
     */
    public void setLastDevice(String lastDevice) {
        this.lastDevice = lastDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.last_ip
     *
     * @return the value of sys_user.last_ip
     *
     * @mbggenerated
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.last_ip
     *
     * @param lastIp the value for sys_user.last_ip
     *
     * @mbggenerated
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.login_num
     *
     * @return the value of sys_user.login_num
     *
     * @mbggenerated
     */
    public Integer getLoginNum() {
        return loginNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.login_num
     *
     * @param loginNum the value for sys_user.login_num
     *
     * @mbggenerated
     */
    public void setLoginNum(Integer loginNum) {
        this.loginNum = loginNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.status
     *
     * @return the value of sys_user.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.status
     *
     * @param status the value for sys_user.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.is_system
     *
     * @return the value of sys_user.is_system
     *
     * @mbggenerated
     */
    public String getIsSystem() {
        return isSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.is_system
     *
     * @param isSystem the value for sys_user.is_system
     *
     * @mbggenerated
     */
    public void setIsSystem(String isSystem) {
        this.isSystem = isSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.update_time
     *
     * @return the value of sys_user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.update_time
     *
     * @param updateTime the value for sys_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_time
     *
     * @return the value of sys_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_time
     *
     * @param createTime the value for sys_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_position
     *
     * @return the value of sys_user.user_position
     *
     * @mbggenerated
     */
    public String getUserPosition() {
        return userPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_position
     *
     * @param userPosition the value for sys_user.user_position
     *
     * @mbggenerated
     */
    public void setUserPosition(String userPosition) {
        this.userPosition = userPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.attr3
     *
     * @return the value of sys_user.attr3
     *
     * @mbggenerated
     */
    public String getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.attr3
     *
     * @param attr3 the value for sys_user.attr3
     *
     * @mbggenerated
     */
    public void setAttr3(String attr3) {
        this.attr3 = attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.attr4
     *
     * @return the value of sys_user.attr4
     *
     * @mbggenerated
     */
    public String getAttr4() {
        return attr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.attr4
     *
     * @param attr4 the value for sys_user.attr4
     *
     * @mbggenerated
     */
    public void setAttr4(String attr4) {
        this.attr4 = attr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.attr5
     *
     * @return the value of sys_user.attr5
     *
     * @mbggenerated
     */
    public String getAttr5() {
        return attr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.attr5
     *
     * @param attr5 the value for sys_user.attr5
     *
     * @mbggenerated
     */
    public void setAttr5(String attr5) {
        this.attr5 = attr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.attr1
     *
     * @return the value of sys_user.attr1
     *
     * @mbggenerated
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.attr1
     *
     * @param attr1 the value for sys_user.attr1
     *
     * @mbggenerated
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.attr2
     *
     * @return the value of sys_user.attr2
     *
     * @mbggenerated
     */
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.attr2
     *
     * @param attr2 the value for sys_user.attr2
     *
     * @mbggenerated
     */
    public void setAttr2(String attr2) {
        this.attr2 = attr2;
    }
}