server:
  port: 8090

spring:
  application:
    name: mksd-prod-users


logging:
  level:
    cn.windawn.mapper: debug

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:windawn@eureka1:7001/eureka,http://admin:windawn@eureka2:7002/eureka,http://admin:windawn@eureka3:7003/eureka
  instance:
    instance-id: mksd-prod-users
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）



info:
  app.name: mksd-prod-users
  company.name: windawn
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

management:
  endpoints:
    web:
      exposure:
        include: '*'
