server:
  port: 80
#eureka:
#  client:
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://admin:windawn@eureka1:7001/eureka,http://admin:windawn@eureka2:7002/eureka,http://admin:windawn@eureka3:7003/eureka

ribbon:
  eureka:
    enabled: false

MKSD-PROD:
  ribbon:
    listOfServers: http://localhost:8080,http://localhost:8081,http://localhost:8082

