server:
  port: 9101
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:windawn@eureka1:7001/eureka,http://admin:windawn@eureka2:7002/eureka,http://admin:windawn@eureka3:7003/eureka

turbine:
  app-config: MKSD-PROD,MKSD-PROD-USERS
  cluster-name-expression: new String("default")
